version: '3.3'

services:
  random-greeting:
    container_name: random-greeting-service
    build: random-greeting
    ports:
     - 9999:9999
    env_file:
     - ./random-greeting/.env
  incubator-roster:
    container_name: incubator-roster-service
    build: incubator-roster
    ports:
     - 8765:8765
  attendance:
    image: mysql/mysql-server:latest
    container_name: attendance
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./attendance/data:/docker-entrypoint-initdb.d
networks:
  default:
    name: local-network