version: '3.3'

services:
  random-greeting:
    container_name: random-greeting-service
    build: random-greeting
    ports:
     - 9999:9999
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:9999/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
  incubator-roster:
    container_name: incubator-roster-service
    build: incubator-roster
    ports:
     - 8765:8765
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8765/healthcheck"]
      interval: 15s
      timeout: 5s
      retries: 3
networks:
  default:
    name: local-network